version: '3.4'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1401:1433"
    volumes:
      - type: 'bind'
        target: '/var/opt/mssql/data'
        source: './docker/sqldata/data'
